apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pacman

resources:
  - namespace.yaml
  - mongo-pvc.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - pacman-deployment.yaml
  - pacman-service.yaml
